import type { Metadata } from 'next'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
import BottomNavigation from '@/components/BottomNavigation'
import ToastProvider from './providers/toast-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
        {/* Container principal avec padding bottom pour la nav */}
        <main className="pb-16 min-h-screen">{children}</main>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
      {/* Barre de navigation fixe */}
      <ToastProvider />
      <BottomNavigation />
    </html>
  )
}
